analytics:
  ua: ''
  gtag: ''
  gtm: ''
  ga_prod: ''
breadcrumbs:
  goal:
    - path: /
      label: general.home
    # - path: /goals
    #   label: general.goals
  indicator:
    - path: /
      label: general.home
    # - path: /goals
    #   label: general.goals
cookie_consent_form:
  enabled: false
country:
  name: Germany
  adjective: German
create_goals:
  previous_next_links: false
  goals: []
create_indicators:
  previous_next_links: false
create_pages:
  - filename: ''
    folder: /goals
    layout: goals
    title: general.goals
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: status.reporting_status
  - filename: ''
    folder: /search
    layout: search
    title: search.search
custom_css: []
custom_js:
  - /assets/js/custom.js
data_edit_url: data
data_fields:
  units: ''
  series: ''
date_formats:
  - type: standard
    language: de
    format: "%d.%m.%Y"
  - type: standard
    language: en
    format: "%b %d, %Y"
disclaimer:
  phase: ''
  message: ''
  hidden: false
email_contacts:
  questions: test@example.com
  suggestions: test@example.com
  functional: test@example.com
environment: staging
footer_language_toggle: none
footer_menu:
  - path: 'mailto:dns-indikatoren@destatis.de' #menu.contactPath
    translation_key: menu.contact_us
  - path: /imprint/
    translation_key: menu.imprint
frontpage_cards:
    - rule_color: grey
      title: ''
      include: components/download-all-data.html
    - rule_color: grey
      title: ''
      include: components/joint_action_column.html
    - rule_color: grey
      title: ''
      include: components/strategy_column.html
frontpage_goals_grid:
    title: frontpage.heading
    description: frontpage.instructions
goal_image_base: 'https://sdg-indikatoren.de/assets/img/goals/dns'
goal_image_extension: ''
goals_page:
  title: general.goals
  description: frontpage.instructions_shorter
graph_color_headline: ['#e5243b', '#dda63a', '#4c9f38', '#c5192d', '#ff3a21', '#26bde2', '#fcc30b', '#a21942', '#fd6925', '#dd1367', '#fd9d24', '#bf8b2e', '#3f7e44', '#0a97d9', '#56c02b', '#00689d', '#19486a']
graph_color_headline_high_contrast: '#55a6e5'
graph_color_set: 'goal'
graph_color_list: []
graph_color_number: 9
graph_title_from_series: false
header_language_toggle: links
hide_empty_metadata: true
hide_single_series: true
hide_single_unit: true
indicator_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/indicator-config
  translation_link: ''
indicator_data_form:
  enabled: true
  repository_link: /tree/develop/data
indicator_metadata_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/meta
  translation_link: ''
  language: ''
  scopes:
    - national
    - global
  exclude_fields: []
  translated: false
indicator_tabs:
  tab_1: ''
  tab_2: ''
  tab_3: ''
  tab_4: ''
languages:
  - de
  - en

observation_attributes:
  - field: COMMENT_OBS_0
    label: ''
  - field: COMMENT_OBS_1
    label: ''
  - field: COMMENT_OBS_2
    label: ''

languages_public: []
logos:
  - src: assets/img/de/DNS_logo.png
    alt: DESTATIS - Deutsche Nachhaltikeitsstrategie
  - language: en
    src: assets/img/en/DNS_logo.png
    alt: DESTATIS - German Strategy for Sustainable Development
map_layers:
  - serviceUrl:  https://Nachhaltige-Entwicklung-Deutschland.github.io/open-sdg-site-starter/assets/maps/boundariesKrs.geojson
    min_zoom: 8
    max_zoom: 11
    staticBorders: true
    subfolder: kreise
    label: indicator.counties
  - serviceUrl:  https://Nachhaltige-Entwicklung-Deutschland.github.io/open-sdg-site-starter/assets/maps/boundaries.geojson
    min_zoom: 0
    max_zoom: 7
    staticBorders: true
    subfolder: laender
    label: indicator.laender
map_options:
  disaggregation_controls: true
  minZoom: 0
  maxZoom: 11
  tileURL: https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
  tileOptions:
    id: mapbox.light
    accessToken: pk.eyJ1IjoibW9ib3NzZSIsImEiOiJjazU1M2trazQwYnFwM2trYmdwNm9rOWxkIn0.u36w-RJPqoTGmivl_zED1w
    attribution: <a href="https://www.openstreetmap.org/copyright">&copy; OpenStreetMap</a> contributors |<br class="visible-xs"> <a href="https://www.bkg.bund.de">&copy; GeoBasis-De / BKG 2024</a> |<br class="hidden-lg"> <a href="https://www.destatis.de/DE/Home/_inhalt.html">&copy; Statistisches Bundesamt (Destatis), 2024</a>
  colorRange: [["#FCE9EB", "#F7BDC4", "#F2929D", "#ED6676", "#E83A4F", "#E5243B", "#B71D2F", "#891623", "#5C0E18", "#2E070C"],
              ["#FCF8EB", "#F7E9C2", "#F2DB9A", "#EDCD72", "#E8BE49", "#E5B735", "#CEA530", "#A08025", "#735C1B", "#453710"],
              ["#EDF5EB", "#C9E2C3", "#A6CF9C", "#82BC74", "#5EA94C", "#4C9F38", "#3D7F2D", "#2E5F22", "#1E4016", "#0F200B"],
              ["#F9E8EA", "#EEBAC0", "#E28C96", "#D65E6C", "#CB3042", "#C5192D", "#9E1424", "#760F1B", "#4F0A12", "#270509"],
              ["#FFEBE9", "#FFC4BC", "#FF9D90", "#FF7564", "#FF4E37", "#FF3A21", "#CC2E1A", "#992314", "#66170D", "#330C07"],
              ["#E9F8FB", "#BEEBF6", "#93DEF0", "#67D1EA", "#3CC4E5", "#26BDE2", "#1E97B5", "#177188", "#0F4C5A", "#08262D"],
              ["#FFF9E7", "#FEEDB6", "#FEE185", "#FDD554", "#FCC923", "#FCC30B", "#CA9C09", "#977507", "#654E04", "#322702"],
              ["#F6E8EC", "#E3BAC6", "#D18CA1", "#BE5E7B", "#AB3055", "#A21942", "#821435", "#610F28", "#410A1A", "#20050D"],
              ["#FFF0E9", "#FED2BE", "#FEB492", "#FE9666", "#FD783B", "#FD6925", "#CA541E", "#983F16", "#652A0F", "#331507"],
              ["#FCE7F0", "#F5B8D1", "#EE89B3", "#E75A95", "#E02B76", "#DD1367", "#B10F52", "#850B3E", "#580829", "#2C0415"],
              ["#FFF5E6", "#FEE2B3", "#FECE80", "#FEBA4D", "#FDA71A", "#FD9D00", "#CA7E00", "#985E00", "#653F00", "#331F00"],
              ["#FAF5EA", "#EFE0C0", "#E4CC96", "#D9B86C", "#CEA342", "#C9992D", "#A17A24", "#795C1B", "#503D12", "#281F09"],
              ["#ECF2EC", "#C5D8C7", "#9FBFA2", "#79A57C", "#528B57", "#3F7E44", "#326536", "#264C29", "#19321B", "#0D190E"],
              ["#E7F5FB", "#B6E0F4", "#85CBEC", "#54B6E4", "#23A1DD", "#0A97D9", "#0879AE", "#065B82", "#043C57", "#021E2B"],
              ["#EEF9EA", "#CCECBF", "#ABE095", "#89D36B", "#67C640", "#56C02B", "#459A22", "#34731A", "#224D11", "#112609"],
              ["#E6F0F5", "#B3D2E2", "#80B4CE", "#4D95BA", "#1A77A7", "#00689D", "#00537E", "#003E5E", "#002A3F", "#00151F"],
              ["#E8EDF0", "#BAC8D2", "#8CA4B5", "#5E7F97", "#305A79", "#19486A", "#143A55", "#0F2B40", "#0A1D2A", "#050E15"]]
  noValueColor: '#f0f0f0'
  styleNormal:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#888888'
    dashArray: ''
  styleHighlighted:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#111111'
    dashArray: ''
  styleStatic:
    weight: 2
    opacity: 1
    fillOpacity: 0
    color: '#172d44'
    dashArray: ''
menu:
  - path: /
    translation_key: menu.1_start
  - translation_key: menu.1_status
    dropdown:
      - path: /status/
        translation_key: menu.1_status_2_methodology
      - path: /status_summary/
        translation_key: menu.1_status_2_overview
  - translation_key: menu.1_strategy
    dropdown:
      - path: /strategy/dns/
        translation_key: menu.1_strategy_2_dns
      - path: /strategy/monitoring/
        translation_key: menu.1_strategy_2_monitoring
      - path: /strategy/publications/
        translation_key: menu.1_strategy_2_publications
      - path: /strategy/links/
        translation_key: menu.1_strategy_2_links
  - path: /laender/
    translation_key: menu.1_laender
  - path: menu.1_global_indicators_path
    translation_key: menu.1_global_indicators
  - translation_key: menu.1_help
    dropdown:
    - path: /help/navigation/
      translation_key: menu.1_help_2_navigation
    - path: /help/guidance/
      translation_key: menu.1_help_2_guidance
    - path: /help/faq/
      translation_key: menu.1_help_2_faq
metadata_edit_url: metadata
metadata_tabs:
  - scope: national
    title: indicator.details
    description: indicator.dns_metadata_blurb
  - scope: content
    title: indicator.contentAndProgress
    description: ''
  - scope: downloads
    title: indicator.downloads
    description: indicator.download_blurb
  - scope: sources
    title: indicator.sources
    description: ''
non_global_metadata: indicator.national_metadata
news:
  category_links: false
progress_status:
  status_heading: ''
  status_types: []
remote_data_prefix: 'https://Nachhaltige-Entwicklung-Deutschland.github.io/open-sdg-data-starter'
reporting_status:
  title: status.reporting_status
  description: status.description
  disaggregation_tabs: false
  status_types:
    - value: complete
      label: status.reported_online
      hide_on_goal_pages: false
    - value: notstarted
      label: status.no_data_available
      hide_on_goal_pages: false
    - value: notapplicable
      label: status.not_applicable
      hide_on_goal_pages: false
repository_url_data: 'https://github.com/Nachhaltige-Entwicklung-Deutschland/open-sdg-site-starter'
repository_url_site: ''
search_index_boost: []
search_index_extra_fields: []
site_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/_data
  translation_link: ''
time_series_attributes:
  - field: COMMENT_TS
    label: indicator.footnote
validate_indicator_config: false
validate_site_config: false
x_axis_label: ''
###
series_toggle: true
graph_title_from_series: false
decimal_separator: ','
thousands_separator: ' '
useHeadlineColor: false
no_value_character: ' '
